spring.application.name=dogs-api

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dogsdb}
spring.datasource.username=${DB_USER:dogs}
spring.datasource.password=${DB_PASSWORD:dogspass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
